In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import set_config
set_config(display='diagram')

In [2]:
data = pd.read_csv('train.csv')
df = data.copy()
df.head(5)
df.shape

(1460, 81)

In [3]:
data_test = pd.read_csv('test.csv')
df_test = data_test.copy()
df_test.head(5)
df_test.shape

(1459, 80)

In [4]:
def df_info(df):
    len_df = len(df)
    all_columns = len(df.columns)
    all_nan = df.isna().sum().sum() 
    
    print(f"""
    Longueur du dataset : {len_df} enregistrements
    Nombre de colonnes : {all_columns}
    """) 
    
    echantillonColonnes = []
    for i in df.columns:
        listcolumn = str(list(df[i].head(5)))
        echantillonColonnes.append(listcolumn)
        echantillonColonnes[0:5]
    obs = pd.DataFrame({'type': list(df.dtypes),
    'Echantillon': echantillonColonnes,
    "% de valeurs nulles":
    round(df.isna().sum() / len_df * 100, 2),
    'Nbr L dupliquées' : (df.duplicated()).sum(),
    'Nbr V unique' : df.nunique()
    })
    return obs

In [5]:
df_info(df)

    Longueur du dataset : 1460 enregistrements
    Nombre de colonnes : 81

,type,Echantillon,% de valeurs nulles,Nbr L dupliquées,Nbr V unique
Id,int64,"[1, 2, 3, 4, 5]",0.00,0,1460
MSSubClass,int64,"[60, 20, 60, 70, 60]",0.00,0,15
MSZoning,object,"['RL', 'RL', 'RL', 'RL', 'RL']",0.00,0,5
LotFrontage,float64,"[65.0, 80.0, 68.0, 60.0, 84.0]",17.74,0,110
LotArea,int64,"[8450, 9600, 11250, 9550, 14260]",0.00,0,1073
...,...,...,...,...,...
MoSold,int64,"[2, 5, 9, 2, 12]",0.00,0,12
YrSold,int64,"[2008, 2007, 2008, 2006, 2008]",0.00,0,5
SaleType,object,"['WD', 'WD', 'WD', 'WD', 'WD']",0.00,0,9
SaleCondition,object,"['Normal', 'Normal', 'Normal', 'Abnorml', 'Nor...",0.00,0,6
SalePrice,int64,"[208500, 181500, 223500, 140000, 250000]",0.00,0,663

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [7]:
df_test = pd.read_csv('test.csv')

In [8]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     1443 non-null   object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [9]:
dfdrop = df.drop(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], axis=1)

In [10]:
def dfdrop_info(dfdrop):
    len_dfdrop = len(dfdrop)
    all_columns = len(dfdrop.columns)
    all_nan = dfdrop.isna().sum().sum() 
    
    print(f"""
    Longueur du dataset : {len_dfdrop} enregistrements
    Nombre de colonnes : {all_columns}
    """) 
    
    echantillonColonnes = []
    for i in dfdrop.columns:
        listcolumn = str(list(dfdrop[i].head(5)))
        echantillonColonnes.append(listcolumn)
        echantillonColonnes[0:5]
    obs = pd.DataFrame({'type': list(dfdrop.dtypes),
    'Echantillon': echantillonColonnes,
    "% de valeurs nulles":
    round(dfdrop.isna().sum() / len_dfdrop * 100, 2),
    'Nbr L dupliquées' : (dfdrop.duplicated()).sum(),
    'Nbr V unique' : dfdrop.nunique()
    })
    return obs

In [11]:
dfdrop_info(dfdrop)

    Longueur du dataset : 1460 enregistrements
    Nombre de colonnes : 76

,type,Echantillon,% de valeurs nulles,Nbr L dupliquées,Nbr V unique
Id,int64,"[1, 2, 3, 4, 5]",0.00,0,1460
MSSubClass,int64,"[60, 20, 60, 70, 60]",0.00,0,15
MSZoning,object,"['RL', 'RL', 'RL', 'RL', 'RL']",0.00,0,5
LotFrontage,float64,"[65.0, 80.0, 68.0, 60.0, 84.0]",17.74,0,110
LotArea,int64,"[8450, 9600, 11250, 9550, 14260]",0.00,0,1073
...,...,...,...,...,...
MoSold,int64,"[2, 5, 9, 2, 12]",0.00,0,12
YrSold,int64,"[2008, 2007, 2008, 2006, 2008]",0.00,0,5
SaleType,object,"['WD', 'WD', 'WD', 'WD', 'WD']",0.00,0,9
SaleCondition,object,"['Normal', 'Normal', 'Normal', 'Abnorml', 'Nor...",0.00,0,6
SalePrice,int64,"[208500, 181500, 223500, 140000, 250000]",0.00,0,663

In [12]:
dfdrop.isnull().sum().sum()

868

In [13]:
def df_test_info(df_test):
    len_df_test = len(df_test)
    all_columns = len(df_test.columns)
    all_nan = df_test.isna().sum().sum() 
    
    print(f"""
    Longueur du dataset : {len_df_test} enregistrements
    Nombre de colonnes : {all_columns}
    """) 
    
    echantillonColonnes = []
    for i in df_test.columns:
        listcolumn = str(list(df_test[i].head(5)))
        echantillonColonnes.append(listcolumn)
        echantillonColonnes[0:5]
    obs = pd.DataFrame({'type': list(df_test.dtypes),
    'Echantillon': echantillonColonnes,
    "% de valeurs nulles":
    round(df_test.isna().sum() / len_df_test * 100, 2),
    'Nbr L dupliquées' : (df_test.duplicated()).sum(),
    'Nbr V unique' : df_test.nunique()
    })
    return obs

In [14]:
df_test_info(df_test)

    Longueur du dataset : 1459 enregistrements
    Nombre de colonnes : 80

,type,Echantillon,% de valeurs nulles,Nbr L dupliquées,Nbr V unique
Id,int64,"[1461, 1462, 1463, 1464, 1465]",0.00,0,1459
MSSubClass,int64,"[20, 20, 60, 60, 120]",0.00,0,16
MSZoning,object,"['RH', 'RL', 'RL', 'RL', 'RL']",0.27,0,5
LotFrontage,float64,"[80.0, 81.0, 74.0, 78.0, 43.0]",15.56,0,115
LotArea,int64,"[11622, 14267, 13830, 9978, 5005]",0.00,0,1106
...,...,...,...,...,...
MiscVal,int64,"[0, 12500, 0, 0, 0]",0.00,0,26
MoSold,int64,"[6, 6, 3, 6, 1]",0.00,0,12
YrSold,int64,"[2010, 2010, 2010, 2010, 2010]",0.00,0,5
SaleType,object,"['WD', 'WD', 'WD', 'WD', 'WD']",0.07,0,9
SaleCondition,object,"['Normal', 'Normal', 'Normal', 'Normal', 'Norm...",0.00,0,6

In [15]:
df_test.isnull().sum().sum()

7000

In [16]:
dfdrop_test = df_test.drop(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], axis=1)

In [17]:
def dfdrop_test_info(dfdrop_test):
    len_dfdrop_test = len(dfdrop_test)
    all_columns = len(dfdrop_test.columns)
    all_nan = dfdrop_test.isna().sum().sum() 
    
    print(f"""
    Longueur du dataset : {len_dfdrop_test} enregistrements
    Nombre de colonnes : {all_columns}
    """) 
    
    echantillonColonnes = []
    for i in dfdrop_test.columns:
        listcolumn = str(list(dfdrop_test[i].head(5)))
        echantillonColonnes.append(listcolumn)
        echantillonColonnes[0:5]
    obs = pd.DataFrame({'type': list(dfdrop_test.dtypes),
    'Echantillon': echantillonColonnes,
    "% de valeurs nulles":
    round(dfdrop_test.isna().sum() / len_dfdrop_test * 100, 2),
    'Nbr L dupliquées' : (dfdrop_test.duplicated()).sum(),
    'Nbr V unique' : dfdrop_test.nunique()
    })
    return obs

In [18]:
dfdrop_test_info(dfdrop_test)

    Longueur du dataset : 1459 enregistrements
    Nombre de colonnes : 75

,type,Echantillon,% de valeurs nulles,Nbr L dupliquées,Nbr V unique
Id,int64,"[1461, 1462, 1463, 1464, 1465]",0.00,0,1459
MSSubClass,int64,"[20, 20, 60, 60, 120]",0.00,0,16
MSZoning,object,"['RH', 'RL', 'RL', 'RL', 'RL']",0.27,0,5
LotFrontage,float64,"[80.0, 81.0, 74.0, 78.0, 43.0]",15.56,0,115
LotArea,int64,"[11622, 14267, 13830, 9978, 5005]",0.00,0,1106
...,...,...,...,...,...
MiscVal,int64,"[0, 12500, 0, 0, 0]",0.00,0,26
MoSold,int64,"[6, 6, 3, 6, 1]",0.00,0,12
YrSold,int64,"[2010, 2010, 2010, 2010, 2010]",0.00,0,5
SaleType,object,"['WD', 'WD', 'WD', 'WD', 'WD']",0.07,0,9
SaleCondition,object,"['Normal', 'Normal', 'Normal', 'Normal', 'Norm...",0.00,0,6

In [19]:
dfdrop_test.isnull().sum().sum()

885

In [20]:
dfd = dfdrop
dfd

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [21]:
dfd_test = dfdrop_test
dfd_test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,...,36,0,0,0,0,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,...,34,0,0,0,0,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,IR1,Lvl,AllPub,Inside,...,36,0,0,0,0,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,IR1,HLS,AllPub,Inside,...,82,0,0,144,0,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,Reg,Lvl,AllPub,Inside,...,24,0,0,0,0,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,...,32,0,0,0,0,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,...,48,0,0,0,0,0,11,2006,WD,Normal

In [22]:
list_of_numerics = dfd.select_dtypes(include = ['float','int']).columns
types = dfd.dtypes
missing = round((dfd.isnull().sum() / dfd.shape[0]),3) * 100
overview = dfd.apply(lambda x: [round(x.min()), 
                                 round(x.max()), 
                                 round(x.mean()), 
                                 round(x.quantile(0.5))] if x.name in list_of_numerics else x.unique())

outliers = dfd.apply(lambda x: sum(
                                 (x<(x.quantile(0.25) - 1.5 * (x.quantile(0.75)-x.quantile(0.25)))) |
                                 (x>(x.quantile(0.75) + 1.5 * (x.quantile(0.75)-x.quantile(0.25))))
                                 if x.name in list_of_numerics else ''))


explo = pd.DataFrame({'Types': types,
                      'Missing%': missing,
                      'Overview': overview,
                      'Outliers': outliers}).sort_values(by = ['Missing%','Types'],ascending=False)
explo.transpose()

,LotFrontage,GarageType,GarageFinish,GarageQual,GarageCond,GarageYrBlt,BsmtExposure,BsmtFinType2,BsmtQual,BsmtCond,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Types,float64,object,object,object,object,float64,object,object,object,object,...,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
Missing%,17.7,5.5,5.5,5.5,5.5,5.5,2.6,2.6,2.5,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Overview,"[21, 313, 70, 69]","[Attchd, Detchd, BuiltIn, CarPort, nan, Basmen...","[RFn, Unf, Fin, nan]","[TA, Fa, Gd, nan, Ex, Po]","[TA, Fa, nan, Gd, Po, Ex]","[1900, 2010, 1979, 1980]","[No, Gd, Mn, Av, nan]","[Unf, BLQ, nan, ALQ, Rec, LwQ, GLQ]","[Gd, TA, Ex, nan, Fa]","[TA, Gd, nan, Fa, Po]",...,"[0, 298, 192, 40, 255, 235, 90, 147, 140, 160,...","[61, 0, 42, 35, 84, 30, 57, 204, 4, 21, 33, 21...","[0, 272, 228, 205, 176, 87, 172, 102, 37, 144,...","[0, 320, 407, 130, 180, 168, 140, 508, 238, 24...","[0, 176, 198, 291, 252, 99, 184, 168, 130, 142...","[0, 512, 648, 576, 555, 480, 519, 738]","[0, 700, 350, 500, 400, 480, 450, 15500, 1200,...","[2, 5, 9, 12, 10, 8, 11, 4, 1, 7, 3, 6]","[2008, 2007, 2006, 2009, 2010]","[208500, 181500, 223500, 140000, 250000, 14300..."
Outliers,88,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
list_of_numerics = dfd_test.select_dtypes(include = ['float','int']).columns
types = dfd_test.dtypes
missing = round((dfd_test.isnull().sum() / dfd_test.shape[0]),3) * 100
overview = dfd_test.apply(lambda x: [round(x.min()), 
                                 round(x.max()), 
                                 round(x.mean()), 
                                 round(x.quantile(0.5))] if x.name in list_of_numerics else x.unique())

outliers = dfd_test.apply(lambda x: sum(
                                 (x<(x.quantile(0.25) - 1.5 * (x.quantile(0.75)-x.quantile(0.25)))) |
                                 (x>(x.quantile(0.75) + 1.5 * (x.quantile(0.75)-x.quantile(0.25))))
                                 if x.name in list_of_numerics else ''))


explo = pd.DataFrame({'Types': types,
                      'Missing%': missing,
                      'Overview': overview,
                      'Outliers': outliers}).sort_values(by = ['Missing%','Types'],ascending=False)
explo.transpose()

,LotFrontage,GarageFinish,GarageQual,GarageCond,GarageYrBlt,GarageType,BsmtCond,BsmtQual,BsmtExposure,BsmtFinType1,...,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Types,float64,object,object,object,float64,object,object,object,object,object,...,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
Missing%,15.6,5.3,5.3,5.3,5.3,5.2,3.1,3.0,3.0,2.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Overview,"[21, 200, 69, 67]","[Unf, Fin, RFn, nan]","[TA, nan, Fa, Gd, Po]","[TA, nan, Fa, Gd, Po, Ex]","[1895, 2207, 1978, 1979]","[Attchd, Detchd, BuiltIn, nan, Basment, 2Types...","[TA, Po, Fa, Gd, nan]","[TA, Gd, Ex, Fa, nan]","[No, Gd, Mn, Av, nan]","[Rec, ALQ, GLQ, Unf, BLQ, LwQ, nan]",...,"[0, 1, 2, 3, 4]","[140, 393, 212, 360, 0, 157, 483, 192, 240, 20...","[0, 36, 34, 82, 84, 21, 75, 68, 30, 133, 35, 7...","[0, 80, 186, 120, 150, 205, 113, 135, 126, 334...","[0, 224, 255, 225, 360, 150, 153, 174, 120, 21...","[120, 0, 144, 256, 216, 204, 160, 240, 148, 16...","[0, 144, 368, 444, 228, 561, 800]","[0, 12500, 500, 1500, 300, 450, 80, 600, 490, ...","[6, 3, 1, 4, 5, 2, 7, 10, 8, 11, 9, 12]","[2010, 2009, 2008, 2007, 2006]"
Outliers,100,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
cols_to_subset = ['LotFrontage', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']

dfd[cols_to_subset].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LotFrontage   1201 non-null   float64
 1   MasVnrType    1452 non-null   object
 2   MasVnrArea    1452 non-null   float64
 3   BsmtQual      1423 non-null   object
 4   BsmtCond      1423 non-null   object
 5   BsmtExposure  1422 non-null   object
 6   BsmtFinType1  1423 non-null   object
 7   BsmtFinType2  1422 non-null   object
 8   Electrical    1459 non-null   object
 9   GarageType    1379 non-null   object
 10  GarageYrBlt   1379 non-null   float64
 11  GarageFinish  1379 non-null   object
 12  GarageQual    1379 non-null   object
 13  GarageCond    1379 non-null   object
dtypes: float64(3), object(11)
memory usage: 159.8+ KB

In [25]:
for col in cols_to_subset:
    p = dfd[col].value_counts()
    print(p)
    print('\n----------------------------------------\n')

60.0     143
70.0      70
80.0      69
50.0      57
75.0      53
        ...
112.0      1
138.0      1
149.0      1
38.0       1
111.0      1
Name: LotFrontage, Length: 110, dtype: int64

----------------------------------------

None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

----------------------------------------

0.0      861
108.0      8
72.0       8
180.0      8
16.0       7
        ...
31.0       1
366.0      1
528.0      1
894.0      1
415.0      1
Name: MasVnrArea, Length: 327, dtype: int64

----------------------------------------

TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64

----------------------------------------

TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

----------------------------------------

No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

----------------------------------------

Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

----------------------------------------

Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: BsmtFinType2, dtype: int64

----------------------------------------

SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

----------------------------------------

Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

----------------------------------------

2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
          ..
1906.0     1
1908.0     1
1933.0     1
1900.0     1
1927.0     1
Name: GarageYrBlt, Length: 97, dtype: int64

----------------------------------------

Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

----------------------------------------

TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: GarageQual, dtype: int64

----------------------------------------

TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

----------------------------------------

In [26]:
cols_to_subset_test = ['LotFrontage', 'Utilities', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'KitchenQual', 'Functional', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'SaleType']
dfd_test[cols_to_subset_test].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LotFrontage   1232 non-null   float64
 1   Utilities     1457 non-null   object
 2   Exterior1st   1458 non-null   object
 3   Exterior2nd   1458 non-null   object
 4   MasVnrType    1443 non-null   object
 5   MasVnrArea    1444 non-null   float64
 6   BsmtQual      1415 non-null   object
 7   BsmtCond      1414 non-null   object
 8   BsmtExposure  1415 non-null   object
 9   BsmtFinType1  1417 non-null   object
 10  BsmtFinSF1    1458 non-null   float64
 11  BsmtFinType2  1417 non-null   object
 12  BsmtFinSF2    1458 non-null   float64
 13  BsmtUnfSF     1458 non-null   float64
 14  TotalBsmtSF   1458 non-null   float64
 15  BsmtFullBath  1457 non-null   float64
 16  BsmtHalfBath  1457 non-null   float64
 17  KitchenQual   1458 non-null   object
 18  Functional    1457 non-null   object
 19  GarageType    1383 non-null   object
 20  GarageYrBlt   1381 non-null   float64
 21  GarageFinish  1381 non-null   object
 22  GarageCars    1458 non-null   float64
 23  GarageArea    1458 non-null   float64
 24  GarageQual    1381 non-null   object
 25  GarageCond    1381 non-null   object
 26  SaleType      1458 non-null   object
dtypes: float64(11), object(16)
memory usage: 307.9+ KB

In [27]:
for col in cols_to_subset_test:
    q = dfd_test[col].value_counts()
    print(q)
    print('\n----------------------------------------\n')

60.0     133
80.0      68
70.0      63
50.0      60
75.0      52
        ...
149.0      1
117.0      1
121.0      1
101.0      1
22.0       1
Name: LotFrontage, Length: 115, dtype: int64

----------------------------------------

AllPub    1457
Name: Utilities, dtype: int64

----------------------------------------

VinylSd    510
MetalSd    230
HdBoard    220
Wd Sdng    205
Plywood    113
CemntBd     65
BrkFace     37
WdShing     30
AsbShng     24
Stucco      18
BrkComm      4
AsphShn      1
CBlock       1
Name: Exterior1st, dtype: int64

----------------------------------------

VinylSd    510
MetalSd    233
HdBoard    199
Wd Sdng    194
Plywood    128
CmentBd     66
Wd Shng     43
BrkFace     22
Stucco      21
AsbShng     18
Brk Cmn     15
ImStucc      5
CBlock       2
AsphShn      1
Stone        1
Name: Exterior2nd, dtype: int64

----------------------------------------

None       878
BrkFace    434
Stone      121
BrkCmn      10
Name: MasVnrType, dtype: int64

----------------------------------------

0.0       877
176.0      10
144.0       9
120.0       8
216.0       8
         ...
166.0       1
292.0       1
113.0       1
39.0        1
1159.0      1
Name: MasVnrArea, Length: 303, dtype: int64

----------------------------------------

TA    634
Gd    591
Ex    137
Fa     53
Name: BsmtQual, dtype: int64

----------------------------------------

TA    1295
Fa      59
Gd      57
Po       3
Name: BsmtCond, dtype: int64

----------------------------------------

No    951
Av    197
Gd    142
Mn    125
Name: BsmtExposure, dtype: int64

----------------------------------------

GLQ    431
Unf    421
ALQ    209
Rec    155
BLQ    121
LwQ     80
Name: BsmtFinType1, dtype: int64

----------------------------------------

0.0       462
24.0       15
602.0       6
276.0       6
16.0        5
         ...
1181.0      1
1094.0      1
354.0       1
1053.0      1
485.0       1
Name: BsmtFinSF1, Length: 669, dtype: int64

----------------------------------------

Unf    1237
Rec      51
LwQ      41
BLQ      35
ALQ      33
GLQ      20
Name: BsmtFinType2, dtype: int64

----------------------------------------

0.0      1278
483.0       3
294.0       3
162.0       3
590.0       2
         ...
344.0       1
799.0       1
495.0       1
530.0       1
620.0       1
Name: BsmtFinSF2, Length: 161, dtype: int64

----------------------------------------

0.0       123
384.0      11
624.0       8
480.0       7
738.0       7
         ...
1065.0      1
1558.0      1
454.0       1
402.0       1
1211.0      1
Name: BsmtUnfSF, Length: 793, dtype: int64

----------------------------------------

0.0       41
864.0     39
960.0     13
672.0     12
768.0     12
          ..
1053.0     1
907.0      1
1050.0     1
1060.0     1
1570.0     1
Name: TotalBsmtSF, Length: 736, dtype: int64

----------------------------------------

0.0    849
1.0    584
2.0     23
3.0      1
Name: BsmtFullBath, dtype: int64

----------------------------------------

0.0    1364
1.0      91
2.0       2
Name: BsmtHalfBath, dtype: int64

----------------------------------------

TA    757
Gd    565
Ex    105
Fa     31
Name: KitchenQual, dtype: int64

----------------------------------------

Typ     1357
Min2      36
Min1      34
Mod       20
Maj1       5
Maj2       4
Sev        1
Name: Functional, dtype: int64

----------------------------------------

Attchd     853
Detchd     392
BuiltIn     98
2Types      17
Basment     17
CarPort      6
Name: GarageType, dtype: int64

----------------------------------------

2005.0    77
2007.0    66
2006.0    56
2004.0    46
2003.0    42
          ..
1918.0     1
1943.0     1
2207.0     1
1932.0     1
1916.0     1
Name: GarageYrBlt, Length: 97, dtype: int64

----------------------------------------

Unf    625
RFn    389
Fin    367
Name: GarageFinish, dtype: int64

----------------------------------------

2.0    770
1.0    407
3.0    193
0.0     76
4.0     11
5.0      1
Name: GarageCars, dtype: int64

----------------------------------------

0.0      76
576.0    50
440.0    47
484.0    34
400.0    33
         ..
345.0     1
292.0     1
721.0     1
738.0     1
485.0     1
Name: GarageArea, Length: 459, dtype: int64

----------------------------------------

TA    1293
Fa      76
Gd      10
Po       2
Name: GarageQual, dtype: int64

----------------------------------------

TA    1328
Fa      39
Po       7
Gd       6
Ex       1
Name: GarageCond, dtype: int64

----------------------------------------

WD       1258
New       117
COD        44
ConLD      17
CWD         8
ConLI       4
Oth         4
Con         3
ConLw       3
Name: SaleType, dtype: int64

----------------------------------------

In [28]:
for col in ('MasVnrType','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1', 'BsmtFinType2', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'Electrical'):
    dfd[col] = dfd[col].fillna('Missing')

for col in ('MasVnrArea', 'GarageYrBlt'):
    dfd[col] = dfd[col].fillna(0)

In [36]:
for col in ('MSZoning', 'Utilities', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'SaleType'):
    dfd_test[col] = dfd_test[col].fillna('Missing')

for col in ('LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'GarageYrBlt', 'GarageCars', 'GarageArea'):
    dfd_test[col] = dfd_test[col].fillna(df_test[col].mode()[0])

In [37]:
dfd['LotFrontage'] = dfd['LotFrontage'].fillna(dfd['LotFrontage'].mean())
dfd_test['LotFrontage'] = df_test['LotFrontage'].fillna(dfd_test['LotFrontage'].mean())

In [38]:
print(dfd.isnull().sum().sum())
print(dfd_test.isnull().sum().sum())

0
0

In [39]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder

from sklearn.impute import SimpleImputer

from sklearn.pipeline import Pipeline

from sklearn.compose import ColumnTransformer

In [40]:
X = dfd.drop(columns=['SalePrice'])
y = dfd.SalePrice

In [41]:
print(data.shape)
print(X.shape)
print(y.shape)

(1460, 81)
(1460, 75)
(1460,)

In [42]:
X_test = dfd_test

In [43]:
#sns.histplot(data=df, x='SalePrice', hue='SalePrice');

In [44]:
ordinal_features = ['MSZoning', 'ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2', 'HeatingQC','Electrical', 'KitchenQual', 'GarageQual', 'GarageCond']
nominal_features= list(set(X.select_dtypes(include='object').columns.values) - set(ordinal_features))
numerical_features = X.select_dtypes(exclude='object').columns.values

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, MinMaxScaler, StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [46]:
numerical_transformer = SimpleImputer(strategy='median')

nominal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

ordinal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
                transformers=[
                    ('num', numerical_transformer, numerical_features),
                    ('cat_nom', nominal_transformer, nominal_features),
                    ('ord_nom', ordinal_transformer, ordinal_features)
                ])

pipe = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('minmaxscaler', MinMaxScaler()),
        ('stdscaler',  StandardScaler()),
        ('regressor', DecisionTreeRegressor(random_state=0, criterion='mse'))
    
])

In [47]:
len(numerical_features) + len(nominal_features) + len(ordinal_features)

75

In [48]:
X_train, X_val, y_train, y_val = train_test_split(X, y, train_size=0.8, random_state=3)

In [49]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='median'),
                                                  array(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF',
       '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath...
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(handle_unknown='ignore'))]),
                                                  ['MSZoning', 'ExterQual',
                                                   'ExterCond', 'BsmtQual',
                                                   'BsmtCond', 'BsmtExposure',
                                                   'BsmtFinType1',
                                                   'BsmtFinType2', 'HeatingQC',
                                                   'Electrical', 'KitchenQual',
                                                   'GarageQual',
                                                   'GarageCond'])])),
                ('minmaxscaler', MinMaxScaler()),
                ('stdscaler', StandardScaler()),
                ('regressor', DecisionTreeRegressor(random_state=0))])

In [50]:
val_predictions = pipe.predict(X_val)

In [51]:
mean_squared_error(y_val, val_predictions, squared=False)

43704.473387383274

In [52]:
mse = mean_squared_error(np.log(y_val), np.log(val_predictions), squared=False) 
print('mse:',mse)

mse: 0.20517285138597968

In [53]:
mean_absolute_error(y_val, val_predictions)

26026.575342465752

In [54]:
pd.DataFrame({'y_val': y_val,
            'val_pred': val_predictions,
             'abs_err': abs(val_predictions-y_val)}).describe()

               y_val       val_pred        abs_err
count     292.000000     292.000000     292.000000
mean   178248.863014  176562.705479   26026.575342
std     70389.950788   70861.202719   35170.078858
min     55000.000000   60000.000000       0.000000
25%    128800.000000  131375.000000    7500.000000
50%    158500.000000  157900.000000   17250.000000
75%    202600.000000  205237.500000   33125.000000
max    466500.000000  556581.000000  396581.000000

# Validation du modele

In [55]:
scores = -1 * cross_val_score(pipe, X, y, cv=5, scoring='neg_mean_absolute_error')

In [56]:
scores

array([29288.1369863 , 26196.07191781, 23568.02739726, 25940.73972603,
       28522.1369863 ])

In [57]:
scores.mean()

26703.022602739726

In [58]:
scores.std()

2032.6466803671844

# Submission

In [59]:
import pandas as pd

In [60]:
ids = pd.read_csv('test.csv')['Id'].astype({'Id':'int32'})
ids

0       1461
1       1462
2       1463
3       1464
4       1465
        ...
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int32

In [67]:
output = pd.DataFrame({'Id':ids, 'SalePrice':dfd['SalePrice']}).fillna(0).astype({'Id':'int32'})
output.to_csv('submissionChabs.csv', index=False)

In [63]:
output

        Id  SalePrice
0     1461     208500
1     1462     181500
2     1463     223500
3     1464     140000
4     1465     250000
...    ...        ...
1455  2916     175000
1456  2917     210000
1457  2918     266500
1458  2919     142125
1459     0     147500

[1460 rows x 2 columns]